Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -3,47 +3,51 @@ version: 0.2
 phases:
   install:
     commands:
-      - echo Logging in to Amazon S3...
-      - echo ${AWS_REGION} ${S3_BUCKET} ${SCRIPT_APP_NAME} ${COMPANY_ID}
-
+      - echo Logging in to Amazon ECR...
+      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+      - echo Installing required tools...
+      - yum install -y docker jq
   pre_build:
     commands:
-      - echo Preparing to zip the build contents...
-      - mkdir -p output
-
+      - echo Pre-build phase: Preparing for Docker image build...
+      - echo Logging in to Docker Hub...
+      - docker login -u sbpraonalla -p $DOCKER_HUB_TOKEN
+      - echo Checking if the ECR repository exists for customer ${CUSTOMER_NAME}...
+      - >
+        REPO_EXISTS=$(aws ecr describe-repositories --region ${AWS_REGION} --query "repositories[?contains(repositoryName, '${CUSTOMER_NAME}')].repositoryName" --output text || echo "not found");
+        if [[ $REPO_EXISTS == "not found" ]]; then
+          echo "ECR repository for ${CUSTOMER_NAME} not found. Creating a new repository.";
+          aws ecr create-repository --repository-name ${CUSTOMER_NAME}-db34320 --region ${AWS_REGION}
+          REPO_EXISTS="${CUSTOMER_NAME}-db34320"
+        else
+          echo "ECR repository found: $REPO_EXISTS";
+        fi
+      - echo Determining branch-specific tag...
+      - |
+        if [[ "${BRANCH_NAME}" == main-* ]]; then
+          BASE_TAG=$(echo "${BRANCH_NAME}" | sed 's/main-//')
+          EXISTING_TAGS=$(aws ecr list-images \
+            --repository-name ${REPO_EXISTS} \
+            --region ${AWS_REGION} \
+            --query "imageIds[?contains(imageTag, '${BASE_TAG}-v')].imageTag" \
+            --output text)
+          MAX_VERSION=$(echo "$EXISTING_TAGS" | grep -oP "${BASE_TAG}-v\K[0-9]+" | sort -nr | head -n 1 || echo 0)
+          NEW_VERSION=$((MAX_VERSION + 1))
+          TAG_NAME="${BASE_TAG}-v${NEW_VERSION}"
+        else
+          TAG_NAME="latest"
+        fi
+      - echo "Using tag: ${TAG_NAME}"
   build:
     commands:
-      - echo Copying build contents to output directory, excluding the output and .git directories...
-      - rsync -av --progress ./ ./output --exclude output --exclude .git
-      - echo Zipping the build contents as code.zip, excluding the .git directory...
-      - cd output
-      - zip -r code.zip . --exclude .git/\*
-
+      - echo Building the Apache Superset Docker image...
+      - docker build .
   post_build:
     commands:
-      - echo Constructing S3 path...
-      - |
-        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/main" ]; then
-          S3_BUCKET_PATH=${S3_BUCKET}
-          echo "Branch is main, using bucket ${S3_BUCKET_PATH}"
-        elif [ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/main-itest" ]; then
-          S3_BUCKET_PATH=${S3_BUCKET_ITEST}
-          echo "Branch is integration-mainline, using bucket ${S3_BUCKET_PATH}"
-        else
-          echo "Branch not recognized, exiting..."
-          exit 0
-        fi
-      - S3_PATH="app=${SCRIPT_APP_NAME}/company=${COMPANY_ID}/code.zip"
-      - echo Uploading code.zip to S3 at path ${S3_PATH}...
-      - aws s3 cp code.zip s3://${S3_BUCKET_PATH}/${S3_PATH}
-      - echo Build and upload to S3 completed successfully.
-
+      - echo Tagging and pushing the Docker image to ECR...
+      - docker tag ${REPO_EXISTS}:${TAG_NAME} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_EXISTS}:${TAG_NAME}
+      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_EXISTS}:${TAG_NAME}
 artifacts:
   files:
-    - code.zip
-  discard-paths: yes
-  base-directory: output
-
-cache:
-  paths:
     - '**/*'
+    - '**/**/**/*'
