with

diff --git a/.github/workflows/superset-e2e.yml b/.github/workflows/superset-e2e.yml
--- a/.github/workflows/superset-e2e.yml
+++ b/.github/workflows/superset-e2e.yml
@@ -133,22 +133,23 @@ jobs:
           PARALLELISM: 6
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           NODE_OPTIONS: "--max-old-space-size=4096"
-        run: |
-          # Hack to run retry at the task level
-          RETRY_COUNT=0
-          MAX_RETRIES=3
+        with:
+          run: |
+            # Hack to run retry at the task level
+            RETRY_COUNT=0
+            MAX_RETRIES=3
 
-          until [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]
-          do
-            cypress-run-all ${{ env.USE_DASHBOARD }} && break
-            RETRY_COUNT=$((RETRY_COUNT+1))
-            echo "Cypress tests failed, retrying... ($RETRY_COUNT/$MAX_RETRIES)"
-          done
+            until [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]
+            do
+              cypress-run-all ${{ env.USE_DASHBOARD }} && break
+              RETRY_COUNT=$((RETRY_COUNT+1))
+              echo "Cypress tests failed, retrying... ($RETRY_COUNT/$MAX_RETRIES)"
+            done
 
-          if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
-            echo "Cypress tests failed after $MAX_RETRIES attempts."
-            exit 1
-          fi
+            if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
+              echo "Cypress tests failed after $MAX_RETRIES attempts."
+              exit 1
+            fi
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
